/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frames;

import static com.mycompany.codificacion.Encriptation.c;
import static com.mycompany.codificacion.Codificacion.findValueInt;
import java.util.ArrayList;
import java.util.Hashtable;
import java.util.Map;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kris_
 */
public class DiccionarioToken extends javax.swing.JFrame {

    /**
     * Creates new form DiccionarioToken
     */
    public static JTable tablaDicc;
    //public static Hashtable<Character, Integer> c = new Hashtable<>();
    
    public DiccionarioToken(Hashtable<Character, Integer> c, ArrayList<Integer> vecPosTrash, ArrayList<Integer> vecDirTrash, String textTrash, int vueltas) {
        initComponents();
        //diccionary();
        Object objDicc[][] = new Object [ c.size() ][2];                
        String colDicc[]={"Caracter [Key]","Número [Value]"};
        int i = 0;
        for (Map.Entry<Character, Integer> entry : c.entrySet()) {
            objDicc [i][0] = entry.getKey();
            objDicc [i][1] = entry.getValue();
            i++;
        }
        i = 0;
        diccionarioTable.setModel(new DefaultTableModel(objDicc,colDicc));
        
        Object objTok[][] = new Object [ vueltas ][6];                
        String colTok[]={"Posicion Dir","Caracter","Valor","Posicion Pos","Caracter","Valor"};
        
        for (int j = 0; j < vueltas; j++) {
            objTok[j][0] = vecDirTrash.get(j);
            objTok[j][1] = textTrash.charAt(vecDirTrash.get(j));
            objTok[j][2] = findValueInt((char)textTrash.charAt(vecDirTrash.get(j)));
            objTok[j][3] = vecPosTrash.get(j);
            objTok[j][4] = textTrash.charAt(vecPosTrash.get(j));
            objTok[j][5] = findValueInt((char)textTrash.charAt(vecPosTrash.get(j)));
        }
        
        tokenTable.setModel(new DefaultTableModel(objTok,colTok));
    }   
    
    /*public static void diccionary(){
        
        c.put('B',0);
        c.put('%',1);
        c.put('!',4);
        c.put('|',5);
        c.put('/',6);
        c.put('<',7);
        c.put(':',8);
        c.put('?',9);
        c.put('>',10);
        c.put('&',11);
        c.put('$',12);
        c.put('*',13);
        c.put(';',14);
        c.put('~',15);
        c.put('A',20);
        c.put('Z',21);
        c.put('T',22);
        c.put('Y',23);
        c.put('a',24);
        c.put('d',25);
        c.put('b',26);
        c.put('v',27);
        c.put('c',28);
        c.put('w',29);
        c.put('X',30);
        c.put('E',31);
        c.put('L',32);
        c.put('n',33);
        c.put('j',34);
        c.put('f',35);
        c.put('G',36);
        c.put('^',37);
        c.put('_',38);
        c.put('Z',39);
        c.put('K',40);
        c.put('p',41);
        c.put('s',42);
        c.put('q',43);
        c.put('o',44);
        c.put('i',45);
        c.put('.',46);
        c.put('-',47);
        c.put('@',48);
        c.put('#',49);
        c.put('=',50);
        
        //System.out.println(c.get('@'));
    }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        principal = new javax.swing.JPanel();
        diccionario = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        diccionarioTable = new javax.swing.JTable();
        token = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tokenTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        principal.setBackground(new java.awt.Color(0, 0, 0));
        principal.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(20, 30, 20, 30), "Diccionario y Token", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(51, 255, 51))); // NOI18N
        principal.setLayout(new javax.swing.BoxLayout(principal, javax.swing.BoxLayout.LINE_AXIS));

        diccionario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Diccionario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(51, 255, 51))); // NOI18N
        diccionario.setLayout(new java.awt.BorderLayout());

        diccionarioTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(diccionarioTable);

        diccionario.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        principal.add(diccionario);

        token.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Token", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(51, 255, 51))); // NOI18N
        token.setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        tokenTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tokenTable);

        jPanel1.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        token.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        principal.add(token);

        getContentPane().add(principal, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DiccionarioToken.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DiccionarioToken.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DiccionarioToken.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DiccionarioToken.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new DiccionarioToken().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel diccionario;
    private javax.swing.JTable diccionarioTable;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel principal;
    private javax.swing.JPanel token;
    private javax.swing.JTable tokenTable;
    // End of variables declaration//GEN-END:variables
}
